apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "chart.fullname" . }}
  name: {{ include "chart.fullname" . }}-cfg
  labels:
    {{- include "chart.labels" . | nindent 4 }}
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "chart.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: /mutate
  failurePolicy: Fail
  name: pull-secrets.k8s.io
  admissionReviewVersions:
  - "v1"
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
  namespaceSelector:
{{ toYaml .Values.namespaceSelector | indent 4 }}
